# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

references:
  tests_steps: &tests_steps
    steps:
      - checkout
      - run:
          name: Install coverage
          command: sudo pip install --upgrade coverage
      - run:
          name: Install Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run coverage test
          command: |
            # notify Code Climate of a pending test report using `before-build`
            ./cc-test-reporter before-build
            # run unit test cases with coverage
            coverage run --source=src setup.py test
            # generate an XML report of coverage results
            coverage xml
            # upload test report to Code Climate using `after-build`
            ./cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $?

  deploy_steps: &deploy_steps
    steps:
      - checkout
      - run:
          name: Install PyPI packaging tools
          command: sudo pip install --upgrade wheel twine
      - run:
          name: Build and upload dist
          command: |
            python setup.py sdist bdist_wheel
            twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*

jobs:
  test-python:
    docker:
      - image: circleci/python
    <<: *tests_steps

  test-python2:
    docker:
      - image: circleci/python:2
    <<: *tests_steps

  test-python3:
    docker:
      - image: circleci/python:3
    <<: *tests_steps

  test-python3.4:
    docker:
      - image: circleci/python:3.4
    <<: *tests_steps

  test-python3.5:
    docker:
      - image: circleci/python:3.5
    <<: *tests_steps

  test-python3.6:
    docker:
      - image: circleci/python:3.6
    <<: *tests_steps

  test-python3.7:
    docker:
      - image: circleci/python:3.7
    <<: *tests_steps

  test-python3.8:
    docker:
      - image: circleci/python:3.8
    <<: *tests_steps

  deploy:
    docker:
      - image: circleci/python
    <<: *deploy_steps

workflows:
  version: 2
  test-and-deploy: # name of your workflow
    jobs:
      - test-python
      - test-python2
      - test-python3
      - test-python3.4
      - test-python3.5
      - test-python3.6
      - test-python3.7
      - test-python3.8
      - deploy:
          requires:
            - test-python3
          filters:
            tags:
              only: /^\d+(\.\d+)*(\.?(a|b|rc|post)\d+(\.\d+)*)?/
            branches:
              ignore: /.*/
