# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

jobs:

  test-cpy27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: python setup.py test
      - store_test_results:
          path: test-reports
      - bdist_wheel

  test-cpy35:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: python3 setup.py test
      - store_test_results:
          path: test-reports

  test-cpy36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python3 setup.py test
      - store_test_results:
          path: test-reports

  deploy:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install --user -r requires/distribute.txt
      - run: python setup.py test
      - store_test_results:
          path: test-reports
      - run: python3 setup.py sdist bdist_wheel
      - run: twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*


workflows:
  version: 2
  test: # name of your workflow
    jobs:
      - test-cpy27
      - test-cpy35
      - test-cpy36
      - deploy:
        requires:
          - test-cpy27
          - test-cpy35
          - test-cpy36
        filters:
          branches:
            only: master
